data_config:
  splits:
    train: 0.8
    valid: 0.1
    test: 0.1
  batch_size: 128

model_config:
  model_name: PNA
  hidden_size: 80
  n_layers: 4
  dropout_p: 0.3
  aggregators:
    - mean
    - min
    - max
    - std
    - sum
  scalers: false
  pretrain_lr: 0.001
  pretrain_epochs: 50
  pretrain_wd: 3.0e-6

shared_config:
  learn_edge_att: true
  precision_k: 5
  num_viz_samples: 8
  viz_interval: 10
  viz_norm_att: true
  extractor_dropout_p: 0.5

GSAT_config:
  method_name: 'GSAT'
  pred_loss_coef: 1
  info_loss_coef: 1
  epochs: 50
  lr: 1.0e-3
  weight_decay: 3.0e-6

  from_scratch: true
  fix_r: false
  decay_interval: 5
  decay_r: 0.1
  final_r: 0.5


DIR_config:
  method_name: 'DIR'
  epochs: 100
  lr: 1.0e-3
  reg: 1.0
  alpha: 1.0e-5
  r: 0.25

GIB_config:
  method_name: 'GIB'
  epochs: 100
  lr: 1.0e-3
  con_weight: 5
  mi_weight: 0.01
  inner_loop: 150

GNNExplainer_config:
  method_name: 'GNNExplainer'
  epochs: 100
  lr: 0.1
  pred_loss_coef: 1
  info_loss_coef: 0.01
  entropy_loss_coef: 1
  info_loss: sum

PGExplainer_config:
  method_name: 'PGExplainer'
  epochs: 100
  lr: 1.0e-3
  freeze_encoder: true
  from_scratch: false
  approx: 'concrete'
  fix_temp: false
  init_temp: 5.0
  hard_st: false
  pred_loss_coef: 1
  info_loss_coef: 0.000078
  entropy_loss_coef: 0.01
  info_loss: sum

GraphMask_config:
  method_name: 'GraphMask'
  epochs: 100
  lr: 1.0e-3
  freeze_encoder: true
  from_scratch: false
  approx: 'hard_concrete'
  fix_temp: true
  init_temp: 0.333
  hard_st: false
  pred_loss_coef: 1
  info_loss_coef: 1
  entropy_loss_coef: 0
  info_loss: mean
  gamma: -0.2
  zeta: 1.0
