_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 77
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 77
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.19.8
            "6": 4.45.2
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
alpha:
    value: 0.0001
beta:
    value: 20
epochs:
    value: 20
gamma_cites:
    value: 0.7
gamma_writes:
    value: 0.5
hidden:
    value: 128
lr:
    value: 0.001
motif:
    value: 1
out_dir:
    value: gsat_hetero_results
per_class:
    value: 100
seed:
    value: 512
temp:
    value: 0.5
